# Generated by Django 5.0.14 on 2026-01-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Yojana Ka Naam')),
                ('description', models.TextField(verbose_name='Choti Jankari')),
                ('link', models.URLField(verbose_name='Website Link (Apply Karne Ke Liye)')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='schemes/', verbose_name='Logo/Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Hai?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
