# Generated by Django 5.0.14 on 2026-02-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Notice / Khabar')),
                ('level', models.CharField(choices=[('DISTRICT', 'Zila Star (Sabke liye)'), ('VILLAGE', 'Gram Star (Sirf ek gaon)')], default='DISTRICT', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Live dikhana hai?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.village', verbose_name='Kis Gaon ke liye?')),
            ],
        ),
    ]
