# Generated by Django 5.0.14 on 2026-02-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notice'),
        ('services', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item ka Naam')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Keemat (Rs)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Item ki Photo')),
                ('description', models.TextField(blank=True, verbose_name='Item ki Jankari')),
                ('is_available', models.BooleanField(default=True, verbose_name='Stock mein hai?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.serviceprovider')),
            ],
        ),
    ]
