# Generated by Django 5.0.14 on 2026-02-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(verbose_name='Doori (KM)')),
                ('from_village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='locations.village')),
                ('to_village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_of', to='locations.village')),
            ],
            options={
                'ordering': ['distance_km'],
                'unique_together': {('from_village', 'to_village')},
            },
        ),
    ]
